privatebin:
  fullnameOverride: privatebin

  podAnnotations:
    configmap.reloader.stakater.com/reload: "privatebin-configs"

  configs:
    conf.php: |
      [main]
      name = "Blyatflix Paste"
      basepath = "https://paste.blyatflix.com/"
      discussion = true
      opendiscussion = false
      password = true
      fileupload = true
      burnafterreadingselected = false
      defaultformatter = "plaintext"
      syntaxhighlightingtheme = "sons-of-obsidian"
      sizelimit = 50000000
      template = "bootstrap"
      expire = "1week"
      templateselection = true
      notice = "Files may be deleted at any time"
      languageselection = true
      languagedefault = "de"
      qrcode = true
      email = true
      icon = identicon

      [model]
      class = Filesystem

      [model_options]
      dir = /srv/data

  image:
    pullPolicy: IfNotPresent

  controller:
    kind: StatefulSet
    pvc:
      accessModes: ReadWriteOnce
      requests: 5Gi
      storageClass: longhorn

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
